version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54321:5432"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=misp"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DATABASE=${DATABASE}
      - OAUTH2_SECRET_KEY=${OAUTH2_SECRET_KEY}
      - OAUTH2_ALGORITHM=${OAUTH2_ALGORITHM}
      - OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES=${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - "./backend:/code"
    entrypoint: [ "bash", "-c", "./entrypoint.sh" ]
    depends_on:
      database:
        condition: service_healthy
