version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-misp}
    ports:
      - "54321:5432"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-misp}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM:-HS256}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
    entrypoint: [ "bash", "-c", "./entrypoint.sh" ]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: poetry run celery -A app.worker.worker worker --loglevel=info
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-misp}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM:-HS256}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
    depends_on:
      - redis
      - postgres
      - api

  flower:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: poetry run celery -A app.worker.worker flower --loglevel=info
    working_dir: /code
    ports:
      - 5555:5555
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-misp}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM:-HS256}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME:-redis}:${REDIS_PORT:-6379}/${REDIS_CELERY_DB:-0}
    depends_on:
      - worker
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      API_HOST: api
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
