version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "54321:5432"
    healthcheck:
      test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
    entrypoint: [ "bash", "-c", "./entrypoint.sh" ]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: poetry run celery -A app.worker.worker worker --loglevel=info
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
    depends_on:
      - redis
      - postgres
      - api

  flower:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: poetry run celery -A app.worker.worker flower --loglevel=info
    working_dir: /code
    ports:
      - 5555:5555
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      OAUTH2_SECRET_KEY: ${OAUTH2_SECRET_KEY}
      OAUTH2_ALGORITHM: ${OAUTH2_ALGORITHM}
      OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES: ${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES}
      CELERY_BROKER_URL: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
      CELERY_RESULT_BACKEND: redis://${REDIS_HOSTNAME}:${REDIS_PORT}/${REDIS_CELERY_DB}
    depends_on:
      - worker
      - redis

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
