version: '3.1'

services:
  api:
    ports:
      - "8080:80"
      - "5677:5677"
      - "5678:5678"
    entrypoint: [ "bash", "-c", "./entrypoint.dev.sh" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    ports:
      - "5679:5679"
    command:
      [
        "sh",
        "-c",
        "poetry run python -m debugpy --listen 0.0.0.0:5679 -m celery -A app.worker.worker worker --loglevel=info"
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
