[tool.poetry]
name = "misp-lite-api"
version = "0.1.0"
description = "MISP, but lightweight"
authors = ["Luciano Righetti <luciano.righetti@circl.lu>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
pymisp = "^2.4.159"
pydantic = "^1.8.0"
sqlalchemy = "^1.4.35"
psycopg2-binary = "^2.9.3"
alembic = "^1.7.7"
python-multipart = "^0.0.5"
python-jose = "^3.3.0"
cryptography = "^37.0.2"
passlib = "^1.7.4"
aiofiles = "^0.8.0"
celery = "^5.2.7"
flower = "^1.0.0"
Jinja2 = "^3.1.2"
redis = "^4.3.3"
debugpy = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
requests = "^2.27.1"
debugpy = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
